"""Create core OLTP schema with RBAC and SSO tables.

Revision ID: a1f3bc0c3e4b
Revises: 819cbf6e030b
Create Date: 2025-01-15 00:00:00

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a1f3bc0c3e4b"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


gender_enum = sa.Enum("male", "female", "other", name="gender_enum")
user_status_enum = sa.Enum("active", "inactive", name="user_status_enum")
license_status_enum = sa.Enum("active", "suspended", "expired", name="license_status")
plan_type_enum = sa.Enum("basic", "standard", "premium", name="plan_type_enum")
payment_status_enum = sa.Enum("paid", "unpaid", "overdue", name="payment_status_enum")
billing_cycle_enum = sa.Enum("monthly", "quarterly", "yearly", name="billing_cycle_enum")
invoice_billing_cycle_enum = sa.Enum(
    "monthly",
    "quarterly",
    "yearly",
    name="invoice_billing_cycle_enum",
)
support_level_enum = sa.Enum("standard", "premium", "enterprise", name="support_level_enum")
support_priority_enum = sa.Enum("low", "medium", "high", "urgent", name="support_priority_enum")
ticket_status_enum = sa.Enum("open", "in_progress", "resolved", "closed", name="ticket_status_enum")
feedback_type_enum = sa.Enum(
    "suggestion",
    "bug",
    "feature_request",
    "other",
    name="feedback_type_enum",
)
feedback_status_enum = sa.Enum("new", "in_review", "implemented", "closed", name="feedback_status_enum")
security_alert_status_enum = sa.Enum("open", "resolved", "dismissed", name="security_alert_status_enum")
security_alert_type_enum = sa.Enum(
    "failed_login",
    "unusual_activity",
    "suspicious_ip",
    "multiple_logins",
    name="security_alert_type_enum",
)
login_method_enum = sa.Enum("standard", "oauth", "sso", "multi_factor", name="login_method_enum")
invoice_status_enum = sa.Enum("pending", "paid", "overdue", name="invoice_status_enum")
payment_method_enum = sa.Enum(
    "credit_card",
    "bank_transfer",
    "paypal",
    "other",
    name="payment_method_enum",
)
subscription_history_status_enum = sa.Enum(
    "active",
    "inactive",
    "cancelled",
    name="subscription_history_status_enum",
)
sso_provider_enum = sa.Enum("google", name="sso_provider_name_enum")

ENUMS = [
    gender_enum,
    user_status_enum,
    license_status_enum,
    plan_type_enum,
    payment_status_enum,
    billing_cycle_enum,
    invoice_billing_cycle_enum,
    support_level_enum,
    support_priority_enum,
    ticket_status_enum,
    feedback_type_enum,
    feedback_status_enum,
    security_alert_status_enum,
    security_alert_type_enum,
    login_method_enum,
    invoice_status_enum,
    payment_method_enum,
    subscription_history_status_enum,
    sso_provider_enum,
]


def upgrade() -> None:  # noqa: D401 - Alembic autogenerated structure
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum in ENUMS:
            op.execute(sa.text(f"DROP TYPE IF EXISTS {enum.name} CASCADE"))


    op.create_table(
        "organization",
        sa.Column("organization_id", sa.Integer(), primary_key=True),
        sa.Column("organization_name", sa.String(length=100), nullable=False, unique=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("license_status", license_status_enum, nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    op.create_table(
        "uuh_permission",
        sa.Column("permission_id", sa.Integer(), primary_key=True),
        sa.Column("permission_name", sa.String(length=50), nullable=False, unique=True),
        sa.Column("permission_description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    op.create_table(
        "uuh_roles",
        sa.Column("role_id", sa.Integer(), primary_key=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False, unique=True),
        sa.Column("role_description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_roles_org"),
    )

    op.create_table(
        "uuh_users",
        sa.Column("user_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("middle_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("username", sa.String(length=128), nullable=False, unique=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.String(length=32), nullable=True),
        sa.Column("gender", gender_enum, nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("profile_img_url", sa.String(length=255), nullable=True),
        sa.Column("nationality", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("status", user_status_enum, nullable=False, server_default="active"),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_users_org"),
        sa.ForeignKeyConstraint(["role_id"], ["uuh_roles.role_id"], name="fk_users_role"),
    )

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_role_permissions_org"),
        sa.ForeignKeyConstraint(["permission_id"], ["uuh_permission.permission_id"], name="fk_role_permissions_perm"),
        sa.ForeignKeyConstraint(["role_id"], ["uuh_roles.role_id"], name="fk_role_permissions_role"),
        sa.PrimaryKeyConstraint("role_id", "permission_id", "organization_id", name="pk_role_permissions"),
    )

    op.create_table(
        "billing_plans",
        sa.Column("plan_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("plan_name", sa.String(length=100), nullable=False, unique=True),
        sa.Column("plan_description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(10, 2), nullable=False),
        sa.Column("billing_cycle", billing_cycle_enum, nullable=False),
        sa.Column("max_users", sa.Integer(), nullable=True),
        sa.Column("max_storage", sa.Integer(), nullable=True),
        sa.Column("support_level", support_level_enum, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("subscription_start", sa.Date(), nullable=True),
        sa.Column("subscription_end", sa.Date(), nullable=True),
        sa.Column("plan_type", plan_type_enum, nullable=False),
        sa.Column("payment_status", payment_status_enum, nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_subscriptions_org"),
    )

    op.create_table(
        "invoices",
        sa.Column("invoice_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(10, 2), nullable=False),
        sa.Column("billing_cycle", invoice_billing_cycle_enum, nullable=False),
        sa.Column("invoice_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", invoice_status_enum, nullable=False),
        sa.Column("payment_method", payment_method_enum, nullable=True),
        sa.Column("payment_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["billing_plans.plan_id"], name="fk_invoices_plan"),
        sa.ForeignKeyConstraint(["school_id"], ["organization.organization_id"], name="fk_invoices_org"),
    )

    op.create_table(
        "usage_metrics",
        sa.Column("metric_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("metric_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_users", sa.Integer(), nullable=True),
        sa.Column("storage_used", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["organization.organization_id"], name="fk_usage_metrics_org"),
    )

    op.create_table(
        "subscription_history",
        sa.Column("subscription_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", subscription_history_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["billing_plans.plan_id"], name="fk_subscription_history_plan"),
        sa.ForeignKeyConstraint(["school_id"], ["organization.organization_id"], name="fk_subscription_history_org"),
    )

    op.create_table(
        "uuh_contact_information",
        sa.Column("address_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False, unique=True),
        sa.Column("email_id", sa.String(length=255), nullable=False, unique=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("verified_phone_number", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("emergency_number", sa.String(length=32), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("street_address", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("zip_code", sa.String(length=16), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_contact_user", ondelete="CASCADE"),
    )

    op.create_table(
        "uuh_user_login",
        sa.Column("login_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_user_login_user", ondelete="CASCADE"),
    )

    op.create_table(
        "uuh_password_reset",
        sa.Column("reset_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reset_token", sa.String(length=255), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("token_used", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_password_reset_user", ondelete="CASCADE"),
    )

    op.create_table(
        "archived_uuh_users",
        sa.Column("archived_user_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_archived_users_org"),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_archived_users_user"),
    )

    op.create_table(
        "support_tickets",
        sa.Column("ticket_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", support_priority_enum, nullable=False),
        sa.Column("status", ticket_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_support_tickets_user"),
    )

    op.create_table(
        "support_ticket_comments",
        sa.Column("comment_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["support_tickets.ticket_id"], name="fk_ticket_comments_ticket", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_ticket_comments_user"),
    )

    op.create_table(
        "system_health_logs",
        sa.Column("log_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("server_uptime", sa.Numeric(5, 2), nullable=True),
        sa.Column("active_users", sa.Integer(), nullable=True),
        sa.Column("storage_usage", sa.Numeric(10, 2), nullable=True),
        sa.Column("cpu_usage", sa.Numeric(5, 2), nullable=True),
        sa.Column("memory_usage", sa.Numeric(5, 2), nullable=True),
        sa.Column("log_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_system_health_logs_org"),
    )

    op.create_table(
        "system_alerts",
        sa.Column("alert_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("alert_message", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("alert_date", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_system_alerts_org"),
    )

    op.create_table(
        "audit_logs",
        sa.Column("log_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("action_description", sa.Text(), nullable=True),
        sa.Column("affected_table", sa.String(length=100), nullable=True),
        sa.Column("affected_row_id", sa.Integer(), nullable=True),
        sa.Column("previous_data", sa.JSON(), nullable=True),
        sa.Column("new_data", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("action_timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_audit_logs_user"),
    )

    op.create_table(
        "user_feedback",
        sa.Column("feedback_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("feedback_type", feedback_type_enum, nullable=False),
        sa.Column("feedback_text", sa.Text(), nullable=False),
        sa.Column("status", feedback_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organization.organization_id"], name="fk_user_feedback_org"),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_user_feedback_user"),
    )

    op.create_table(
        "user_login_activity",
        sa.Column("login_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("login_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("login_ip_address", sa.String(length=45), nullable=True),
        sa.Column("device_info", sa.String(length=255), nullable=True),
        sa.Column("login_success", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("failed_attempt_count", sa.Integer(), nullable=True),
        sa.Column("login_method", login_method_enum, nullable=False),
        sa.Column("login_location", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_login_activity_user"),
    )

    op.create_table(
        "user_activity_logs",
        sa.Column("activity_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_type", sa.String(length=100), nullable=False),
        sa.Column("activity_description", sa.Text(), nullable=True),
        sa.Column("activity_timestamp", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_activity_logs_user"),
    )

    op.create_table(
        "security_alerts",
        sa.Column("alert_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("alert_type", security_alert_type_enum, nullable=False),
        sa.Column("alert_message", sa.Text(), nullable=False),
        sa.Column("alert_status", security_alert_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_security_alerts_user"),
    )

    op.create_table(
        "sso_providers",
        sa.Column("provider_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sso_provider_enum, nullable=False),
        sa.Column("provider_uid", sa.String(length=255), nullable=False, unique=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["uuh_users.user_id"], name="fk_sso_providers_user", ondelete="CASCADE"),
    )


def downgrade() -> None:  # noqa: D401 - Alembic autogenerated structure
    op.drop_table("sso_providers")
    op.drop_table("security_alerts")
    op.drop_table("user_activity_logs")
    op.drop_table("user_login_activity")
    op.drop_table("user_feedback")
    op.drop_table("audit_logs")
    op.drop_table("system_alerts")
    op.drop_table("system_health_logs")
    op.drop_table("support_ticket_comments")
    op.drop_table("support_tickets")
    op.drop_table("archived_uuh_users")
    op.drop_table("uuh_password_reset")
    op.drop_table("uuh_user_login")
    op.drop_table("uuh_contact_information")
    op.drop_table("subscription_history")
    op.drop_table("usage_metrics")
    op.drop_table("invoices")
    op.drop_table("subscriptions")
    op.drop_table("billing_plans")
    op.drop_table("role_permissions")
    op.drop_table("uuh_users")
    op.drop_table("uuh_roles")
    op.drop_table("uuh_permission")
    op.drop_table("organization")

    bind = op.get_bind()
    for enum in reversed(ENUMS):
        enum.drop(bind, checkfirst=True)
